[project]
name = "vibecoding-ollama-function-calling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain==0.3.7",
    "langchain-chroma>=0.2.2",
    "langchain-community>=0.3.7",
    "langchain-ollama>=0.3.3",
    "protobuf<=3.20.3",
    "pypdf>=6.12.2",
    "sentence-transformers>=5.5.1",
    "streamlit>=1.58.0",
]
